language: node_js
node_js:
  - "4"
  - "5"
  - "6"

notifications:
  slack:
    rooms:

      # engineering-webdev
      - secure: "oPUbSL41Iqqdk7lOIuLyJ4F1Z/Mx3yWQl8lzhaJBoL3CZvLHhFnhGZF1vqTJ1635jH9lrGaDZdIxZd/kPMD5YXEXDNKAEnfztdWU/RTt08yIbQt5vYjs4Cpf1yp2LCoqMw6KhQOMc9fLsBnJIgAmyyAYdX7/qn9R1ASRZEZG/Ix7Zx93u35TOM+yVbsg5H4X5X4QPg+kbmJzBO+DzHDKk0E6Awh/DWjwVBlVu2TozlOq/8FPCTRDHxuNwa+arXH87MY9Pk3iPW53si2xy1J7dDiJXqcGTxoOQoase9tLlPexuQSPgoeLp44XO/YY6JkW5ozaRGQ45P2nrNrBG0CNb2yNrS0wMCk7swLfr48tCuIc13MiNqDkDo7GsLolriuOxAxKZhNn1JpnKN+4PoxYhoyWPglynf0FBtgdeIQPUf6cuc+KBnay7smm+8iK5SNH+7dGaH8orjKW3vHNT+KOYMdVt9HpsTB0UFFCnkq6zqlFEhZWM882JGgQhkN1PkR2miQ02JU0/MYT9pFAQOVbuqorS/O7ipxPo27dO59dM9qX+th2XPmOyJaoDjp3cKlWzUHkUAt+OkqWcLh5+2smnEq8WPaGEfAdJGRWXj1E+twHV8ExK5saLlMm6e5P0i/Ecd/VLQRjDjSxaoBJoLBRz3ogTS2H3Z7quQEAQGMux14="
cache:
  directories:
    - $HOME/.npm

before_install:
  - npm -g install npm@3

install:
  - npm install

script:
  - npm run inspect
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)
