language: node_js
node_js:
  - "4"
  - "5"
  - "6"

notifications:
  slack:
    rooms:

      # engineering-frontend
      - secure: "FO7BqSkrYoOMHauOj3Km9ZzFxOhn70tHIux61S16napWrZC4gXg8IglIaKg/9GoTz9CWx+Rr+wjOBl37QxfdKrpzVHfBDFW/D6sAqstTdZxohBa478AlXgaPmDSY7crdHVeKAyAuf/p2iyOtAPl1/GRGS+l3Z9g0/SXuDFzkRUAzvRCd6nlVQnBkg07tgYqAiM/2d+8YdGyeqFX2PoEMmN+eCqYDga5Sv4rlFQiKNSuTkVmLF+9EJ4uFlsBnQbh0+UzG1DJPU3gGEWvkC49DBYgOtKWIPLE5X6aNtEbgqK8sL4UV9agDsYcCStPTIx5gfYSrQsAJwMyRAhzaWre8flYV35E5sBAgGf0GGlWS0GZzDi6TQ2SnJEtViqF7hq9AWRp6rvAqfrfqvN/Nh0LpgGH/udFFZdSgVeK2JR5gHk0NG89NGSlyIlDXflJG1PvHLXbhn8J4GzD2XjB+G+4qkE/0qeoavQxFxehTie6MZpeeaBmdoSXbDxKD7lh7iKWn2w3yYNW3e1ueTMjeo2bEYJ6c0Rt0ptsPb9kt/rAGhlCdgjfnPUms3UlPdWdCWdXdBBDdpP/RTDi3rPAuY9ak1+KpSVyjfgFlXGsqRXf6I4SZ7DJdV4p+1rzoauQXStoWrugGiqDhWeOUZ0W+nXcc8Mrgzo4iRKY2X43P+OHV09Q="
cache:
  directories:
    - $HOME/.npm

before_install:
  - npm -g install npm@3

install:
  - npm install

script:
  - npm run inspect
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)
