language: node_js
node_js:
  - "4"
  - "5"
  - "6"

notifications:
  flowdock:
    secure: "lkbpYuhiY/uWeD/O/4OLmDkKkxo/Ws4XP+25swdK6z5LWM0SVrGVdVyLVz6zBV0iopGkq6CDIsdeNbcW5a/Nl6in9QFoBnF8XHDbXplTDevedDLmdYZIOuGRJ8YuxbIPkYNmNmAyKWMzKhdjyzAX25j7F+lueZEp0YHLKQytQgjPHqFeDJ1hnX7QMIiL60XBWr+OgHbDdQCRJtHjKy+LfGvx22FW96x6HVpoxffGEjGkhV/lS8smjiRmw1XBvhJFaWdjrYQkxbrgJ2tBZsybm1ObVRLhtPxuLai28CwXyQpKC/u5TyUhHuM4CMYRrAMNaKOtzBIRVeNN2zZKPYbl8Li5KgugVXMtbHc+6Nkbnzs7upqNI/eFtY2+yhhXdnecVa75bbDsRM2EyfVNbuyjaDdbnTCP9oMQ6fmvvn5pnuSnFON03lpD65u/y18umdMzjtu2PzNoc8bfqVWxWE43GEn3PzIaCG+yRYezB+4hHlfwW1BqOpY/V7buiFgut7GwFV59ke6kfsBK3nuckOAqp4gQpiLCceToJ2l0eD/Y82QGY7Xp9k7ZPhRT5bwZGDaxZoeMQvx8tTh/C/7DBuR+qm3XVpJqNO/CzOJeUs2bHxyZETeWowO8Gu6wR3FLBslL4uOpk36fr0VJrT3nm5fM/iX8JAvITG5W8h+k0ZMG24A="
  email:
    recipients:
      - secure: "PA08jIIQpRoaFT+hqao1SZJPoVpj1s0mzyH51t95VTNSdR1KMorSzJM7Zn66jt6TtlxX/TQdNFMgX2e6b+6WZF15nV+s6Au9OWHNHN7B/4NqAoSP6rTTTgKp1IUFq/+r8KKktureYleAM8CVSnlP40ILDFT8aTHsPFdi8y4Y4T6w1Q/OeCurDKgL2TNhSKfhp0RF4WQV1/jdBddf7ZYfEO3xvFubUw0w8ae9ebKbRvZI/oJW0AeL+DoTyKbbnN0nOgEdCEcmhUEVAc+Lkpa97GWurPeXjSaVMNjMkfRXPA0t9VN8qssIVZmf5ra42/hVTplDnS7Wq8iJcYZk6zf/fvgNVbDl0eoi9o/aSRGIOzjs/6ULRCWvp+NZU6zNZiuYXWv6I4jersv5TvRgn4lxLZJoTOrKXiekaaP5CToDXE93c+/usRUT/DkjUn8jc0a7TZCGjs8qXZr5XU9X2he4UDs5pTsWlIrOUCh1Kb8eebYsr61RM0GXEcK26w6uAF2oi2qhrnl8iBtPkKCN6XsY0pyaDXdqlQSHMZKKz6/x6yNAXvNJsbOL1+/txqnFiZVFfPq3blt79TpZ9RAooVJgLBT0U55wi+YZ7M4mHhHN6s2v2S+eNzl2LYvA3Yulj1/oaIMmHn2Wz0/zwKYxyvGzOv3DG+QbYmHcousUbSIyoCE="
    on_success: change
    on_failure: always

cache:
  directories:
    - node_modules

before_install:
  - npm -g install npm@3

install:
  - npm install

script:
  - npm run inspect
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)
